version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  debezium:
    image: debezium/connect:1.3
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: _debezium_config
      OFFSET_STORAGE_TOPIC: _debezium_offsets
    links:
      - kafka
    restart: on-failure
    depends_on:
      - kafka
