services:
  # TODO: healthcheck
  kconnectex_kafka:
    container_name: kconnectex_kafka
    image: confluentinc/cp-kafka:7.7.5
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: "kconnectex"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENERS: "BROKER://:9092,CONTROLLER://:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kconnectex_kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
  # TODO: healthcheck
  kconnectex_debezium:
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kconnectex_kafka:9092
      CONFIG_STORAGE_TOPIC: _kconnectex_debezium_config
      OFFSET_STORAGE_TOPIC: _kconnectex_debezium_offsets
    links:
      - kconnectex_kafka
    restart: on-failure
    depends_on:
      - kconnectex_kafka
