services:
  kconnectex_kafka:
    image: "confluentinc/cp-kafka:7.7.5"
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      CLUSTER_ID: "kconnectex"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kconnectex_kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kconnectex_kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b kconnectex_kafka:9092 1 1"]
      interval: "5s"
      timeout: "5s"
      retries: 12
    volumes:
      - kconnectex_kafka_data:/var/lib/kafka/data
  kconnectex_kafkaconnect:
    image: "confluentinc/cp-kafka-connect:7.7.5"
    ports:
      - 8083:8083
    environment:
      CONNECT_GROUP_ID: "1"
      CONNECT_BOOTSTRAP_SERVERS: "kconnectex_kafka:9092"
      CONNECT_CONFIG_STORAGE_TOPIC: "_kconnectex_config"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: "_kconnectex_offsets"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: "_kconnectex_status"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "${CONNECT_PLUGIN_PATH},/usr/share/filestream-connectors"
    depends_on:
      kconnectex_kafka:
        condition: "service_healthy"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8083/connectors || exit 1"]
      interval: "5s"
      timeout: "5s"
      retries: 12
volumes:
  kconnectex_kafka_data:
