version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: debezium/kafka:1.3
    ports:
      - 9092:9092
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
  debezium:
    image: debezium/connect:1.3
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: _debezium_config
      OFFSET_STORAGE_TOPIC: _debezium_offsets
    restart: on-failure
    depends_on:
      - kafka
