version: "3.7"
services:
  kconnectex_zookeeper:
    container_name: kconnectex_zookeeper
    image: debezium/zookeeper:1.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
  kconnectex_kafka:
    container_name: kconnectex_kafka
    image: debezium/kafka:1.8
    ports:
      - 9092:9092
    links:
      - kconnectex_zookeeper
    environment:
      ZOOKEEPER_CONNECT: kconnectex_zookeeper:2181
    depends_on:
      - kconnectex_zookeeper
  kconnectex_debezium:
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kconnectex_kafka:9092
      CONFIG_STORAGE_TOPIC: _kconnectex_debezium_config
      OFFSET_STORAGE_TOPIC: _kconnectex_debezium_offsets
    links:
      - kconnectex_kafka
    restart: on-failure
    depends_on:
      - kconnectex_kafka
