#!/bin/bash

exec docker run \
  --interactive --tty --rm \
  --volume "${HOME}/.kconnectex.json":"/home/app/.kconnectex.json" \
  --volume "$(pwd)/.kconnectex.json":"/home/app/kconnectex/.kconnectex.json" \
  --network host \
  "quay.io/jmks/kconnectex:0.3.0" "$@"
